# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            
tagline:          
description:      
url:             

author:
  name:           'Neil Anderson'
  url:            https://twitter.com/NeilAnders0n

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/eneiand
